export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  safefyPublicKey: process.env.SAFEFY_PUBLIC_KEY ?? "",
  safefySecretKey: process.env.SAFEFY_SECRET_KEY ?? "",
  safefySandboxPublicKey: process.env.SAFEFY_SANDBOX_PUBLIC_KEY ?? "",
  safefySandboxSecretKey: process.env.SAFEFY_SANDBOX_SECRET_KEY ?? "",
  safefyTestMode: process.env.SAFEFY_TEST_MODE === "true",
  safefyOfflineMode: process.env.SAFEFY_OFFLINE_MODE === "true",
};
